name: Composer

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - run: composer install --prefer-dist

    - run: composer test